### ISSUE TITLE
End Towers (Structure)

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#10]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Add a structure called the End Tower or something. It will be just like the the End Houses, but more of a tower look. They have chests at the very top and just like the End Houses may be booby trapped. The tower uses pretty much of the same materials as the End Houses as well. There is a ladder in the middle that allow passage upwards through the tower. The tower could prove useful for pvp combat in the end as players fight one another. 

**Describe alternatives you've considered**
Change the anything as you see fit.

**Additional context**
### End Tower
![2020-06-10_17 54 46](https://user-images.githubusercontent.com/51402617/84323192-588d4300-ab44-11ea-9b36-112784df9617.png)
Description Example: A tower made of Purpur and End Bricks that seems to have been used as a lookout post. Some might be booby-trapped!

### End Tower [shader]
![2020-06-10_17 54 31](https://user-images.githubusercontent.com/51402617/84323219-64790500-ab44-11ea-8926-48ac6fa802af.png)

### End Tower First/Ground Floor
![2020-06-10_17 54 55](https://user-images.githubusercontent.com/51402617/84323245-72c72100-ab44-11ea-82ee-8e83027516b7.png)

### End Tower Second Floor
![2020-06-10_17 55 01](https://user-images.githubusercontent.com/51402617/84323337-9be7b180-ab44-11ea-800b-56bfa0bedf89.png)

### End Tower Final Floor
![2020-06-10_17 47 27](https://user-images.githubusercontent.com/51402617/84323418-c3d71500-ab44-11ea-9350-d14121e2cce1.png)
Note: Loot in chest? Could be loot like in the End Houses or maybe loot that would be found in lookout towers like arrows, bows, and such.

### End Tower Final Floor Booby-Trap
![2020-06-10_17 47 43](https://user-images.githubusercontent.com/51402617/84323492-e23d1080-ab44-11ea-9372-a2249670d641.png)
Note: Chance of being booby-trapped like the End Houses. One TNT is set off by the trap chest in which will start a chain reaction to set off the other ones

**Comment by GucciPoochie** [comment]
**End Tower**
![Tower2](https://user-images.githubusercontent.com/58349185/84384212-7f7a6200-aba2-11ea-8b41-225d001dfc58.png)
Basically I redid the entire design, so now it is more fitting with the rest of the structures and includes the quartz-pillar motif that I have in every building I've done.

**Tower Top**
![2020-06-11_05 11 36](https://user-images.githubusercontent.com/58349185/84384761-51e1e880-aba3-11ea-9d95-f65eb63b6212.png)
![Tower top](https://user-images.githubusercontent.com/58349185/84384635-1cd59600-aba3-11ea-9ac0-033dfe040e1a.png)
The top is fit for combat I believe, and also has a tnt trap that activates when the chest is opened.
There will also probably be a version without the trap as well.

**Comment by GucciPoochie** [comment]
*the design is subject to change

**Comment by DeathShadez** [comment]
Nice. Definitely fits better

**Comment by dfsek** [comment]
Released with 3.2.0
