### ISSUE TITLE
Obsidian Isles Biome

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#11]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Just suggesting a new biome that would be known as the Obsidian Isles or something like that. Sorta like a variation of the regular end isles, but the isles are made of obsidian. The isles can also consist of these crystal spikes that emerge form the obsidian isles or may just be a variation of regular obsidian isles. Maybe obsidian variants of skulker nests and end houses will spawn. idk.

**Describe alternatives you've considered**
Adapt or change the idea to how you seek fit.

**Additional context**
I might add more onto this idea at a later date.

Pictures below of different attempts and revisions. Go with whatever seems to be the best overall.

### Crystal Spikes
![2020-06-10_22 07 01](https://user-images.githubusercontent.com/51402617/84337110-c8142a00-ab66-11ea-9c86-5b301b18941f.png)

### Crystal Spikes | carpet
![2020-06-10_22 09 48](https://user-images.githubusercontent.com/51402617/84337302-378a1980-ab67-11ea-8928-c3cf9f294854.png)
Note: could supply carpet to players in the end :/

### Crystal Spikes | more glass
![2020-06-10_22 14 42](https://user-images.githubusercontent.com/51402617/84337561-df074c00-ab67-11ea-8e77-1f0c96dbcac8.png)
Note: A bit much of glass :/

### Crystal Spikes | end rods
![2020-06-10_22 28 05](https://user-images.githubusercontent.com/51402617/84338326-bed88c80-ab69-11ea-9a3a-00516f860d9f.png)

### Crystal Spikes | Purple Concrete
![2020-06-10_23 06 47](https://user-images.githubusercontent.com/51402617/84340647-23e2b100-ab6f-11ea-8a45-a1f4d2e59cb5.png)

### Shattered Isles?
![2020-06-10_22 47 00](https://user-images.githubusercontent.com/51402617/84339405-61920a80-ab6c-11ea-9688-9e0c2164734d.png)
Note: ¯\_(ツ)_/¯

**Comment by dfsek** [comment]
This would not be very implementable without rewriting the entire way i do biomes; I currently handle material changed in different biomes by sticking Void between them (think the End and Aether). The only way to implement this would be to add additional Void, which I think would be too much.
