### ISSUE TITLE
Unnamed | Void Vines Biome 

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#12]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
A new biome that adds these twisty glass crystals to regular looking end islands (I call them Void Vines idk). The draft biome name I have for it is _End_Vineyard_ or the _Corrupted_End_. I really don't know what to call it, but maybe you can come up with a better name along with picking the best look and lil details. Looks cool I guess. Maybe have them be generated alongside chorus plants in between them and all.

**Describe alternatives you've considered**
Adapt or change the idea in whatever shape or form to which you seek fit.

**Additional context**
### _Corrupted_End_ (or something like that)
![2020-06-12_03 02 41](https://user-images.githubusercontent.com/51402617/84476394-0e978080-ac5c-11ea-94a2-1e19056a4637.png)
Note: Void vines are twisty as they are shifty and stuff. They can be or look like they are going through the island as they come from all around the island.

 ### With Shaders (Different perspective to look at I guess)
![2020-06-12_03 02 58](https://user-images.githubusercontent.com/51402617/84476603-633afb80-ac5c-11ea-9ebf-8894eadb9f3e.png)

### Some completely cut off?
![2020-06-12_03 27 05](https://user-images.githubusercontent.com/51402617/84476766-9ed5c580-ac5c-11ea-890b-1d255bad8d7a.png)
![2020-06-12_03 27 13](https://user-images.githubusercontent.com/51402617/84476772-a2694c80-ac5c-11ea-8a3b-beab26d51b5b.png)
Note: Maybe? I'm not sure, but just some detail to think about.

### Probably with Chorus Plants
![2020-06-12_12 52 02](https://user-images.githubusercontent.com/51402617/84526622-b25c4d00-acab-11ea-97ac-5a891da07e30.png)

--------------------------
### Don't like the vine design? | Some alternatives or go with your own
I made these in case the vines need more spice or a different look. Hard to come up with new stuff that doesn't look too repetitive and not completely crazy in order to get it just right. Just depends on preference and how the audience will look at it.

![2020-06-12_02 45 10](https://user-images.githubusercontent.com/51402617/84476944-df354380-ac5c-11ea-9185-326a657516cf.png)
Note: This pic was a draft that consists with a black glass integration

### Bits of End Stone
![2020-06-12_03 29 51](https://user-images.githubusercontent.com/51402617/84477099-1a377700-ac5d-11ea-8edf-8f7a3f28f0f7.png)
Note: Eh. Not likely

### Bits of Glow Stone
![2020-06-12_03 30 04](https://user-images.githubusercontent.com/51402617/84477163-36d3af00-ac5d-11ea-8d54-1e7ccdf11657.png)
Note: Not likely either

### Inside Glow Stone
![2020-06-12_03 30 10](https://user-images.githubusercontent.com/51402617/84477178-3c30f980-ac5d-11ea-9658-fa299e02e474.png)

### Bits of Obsidian
![2020-06-12_03 30 18](https://user-images.githubusercontent.com/51402617/84477197-42bf7100-ac5d-11ea-822f-831821564a42.png)
Note: Same palette scheme as the shattered forest. Maybe?

### Spikes!
![2020-06-12_03 30 26](https://user-images.githubusercontent.com/51402617/84477682-03455480-ac5e-11ea-8a21-72d7b84718d8.png)
Note: End rods.

### Complete End Stone
![2020-06-12_03 30 34](https://user-images.githubusercontent.com/51402617/84477700-0b9d8f80-ac5e-11ea-9a01-5bd7415a82db.png)
![2020-06-12_13 28 25](https://user-images.githubusercontent.com/51402617/84530214-c0f93300-acb0-11ea-8d11-dd8d6054f106.png)
Note: Interesting.

### Complete End Stone with purpur
![2020-06-12_03 30 38](https://user-images.githubusercontent.com/51402617/84478196-e5c4ba80-ac5e-11ea-8766-cb010bf71bd5.png)
![2020-06-12_13 27 54](https://user-images.githubusercontent.com/51402617/84530163-acb53600-acb0-11ea-8ae3-4dc35e85bcd4.png)
Note: Added some contrast with purpur.

I understand if this feature suggestion may seem a bit too repetitive or too wacky that it will be declined. Just a swing and possible miss I suppose.

I continue to enjoy the work and effort you put into this plugin and look forward to its development.

**Comment by dfsek** [comment]
I don't really think this works. The vines really clash with the flat surface of the islands. Might work in the Shattered End? We still have a Climate variation open for the Shattered End, so this could be the warm climate version of the Shattered Forest, perhaps.

**Comment by DeathShadez** [comment]
Yea. That will probably work better.

**Comment by dfsek** [comment]
This is most likely not going to be worked on. Will reopen if I have any ideas.
