### ISSUE TITLE
Boss Respawns

### ISSUE THREAD

**Issue by Weymouth87** [dfsek/BetterEnd-Public#13]
**Is your feature request related to a problem? Please describe.**
In a server with a large player base, having a limited amount of bosses to kill can make players unhappy.
**Describe the solution you'd like**
An option (as discussed in Discord) to implement a configurable timer for bosses to respawn and to enable "unbreakable" chests to ensure that the spawn chests cannot be removed. (breakable with a confirm command)
**Describe alternatives you've considered**
I dont know if its possible, but maybe have the loot in the dungeon respawn too? 
**Additional context**

**Comment by dfsek** [comment]
Since this feature is mainly aimed towards large servers, it will most likely be Premium-only.
