### ISSUE TITLE
Phantom Nests (Structure) | Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#14]
**Is your feature request related to a problem? Please describe.**
Not really as the problem doesn't pertain to the plugin itself.

**Describe the solution you'd like**
Just gonna cover some points on why I came up with. There are many plugins out there that nerf or take out phantoms to the point that you never see them ever as they are pesky and great annoyances. Phantoms provide phantom membrane that can be used to repair elytras. I know you can use mending on an elytra, but still a point to cover. The Aether I feel could be a great place for these guys to appear and cause some mischief. The structure I have planned will be the Phantom Nest or whatever you plan to call it. This is based off of the Shulker Nest. The Phantom Nest will be in the sky within the Aether biome among the clouds I guess. I don't know the exact limits or possibilities with phantoms unlike Shulkers. A spawner is probably unlikely maybe? It could be taken over and turned into a grinder, but some servers have plugins that make grinders not work. Spawn phantoms in a way that works if there are none, then welp. Nvm. The phantom nests could be a flying island of a sorts with a stone brick ruin or worn down gold dungeon. There could also be  chest maybe? If so, maybe phantom membrane, gold, iron, rare diamonds, and potion stuff? Maybe no chest at all as phantoms only seem to attack those who haven't slept or died recently. You decide. I remember hearing about this on the discord, but it was never put frontward. Probably also a config option to disallow phantoms as some people may never want to ever see phantoms

**Describe alternatives you've considered**
Adapt or change this idea to however you seek fit.

**Additional context**
No pictures at the moment. I don't wanna delve into this if not possible in some manner along with not being able to create these references at the current moment.

**Comment by dfsek** [comment]
That is a good idea - I don't know about the structures tho. Working on a way to implement biome-specific mob spawns (with MythicMobs) so it could probably be done with that.

**Comment by dfsek** [comment]
MythicMobs spawning system as mentioned above is pending release.

**Comment by dfsek** [comment]
Released in 3.3.0
