### ISSUE TITLE
Aether Highlands Mountains

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#15]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Mountains in the Aether Highlands? Might be difficult with the way how some islands are small along with how it may interfere with the Aether Highland Forests. These mountains would bring up the landscape of the Aether Highlands to be higher I guess, but I wouldn't want to ruin the simplicity of the landscape being flat so idk? This could be its own biome possibly, but that completely depends on how you plan to go about it. Design the mountain as whatever you feel best if this idea fits.

**Describe alternatives you've considered**
Adapt or change this idea to how you see fit.

**Additional context**
No pictures at the moment.

**Comment by dfsek** [comment]
This could be interesting; we could put it on the opposite Climate end from the Highlands Forest, possibly.

**Comment by DeathShadez** [comment]
Just a detail to think about, but what do you think about llamas being able to spawn on these mountains as they can in the overworld?

**Comment by dfsek** [comment]
I tried something out - mountains really don't work with the island generation. Besides, the 2 open biome spots are being taken by Birch and Birch Forest biomes. Gonna close this for now, will reopen if I am able to get it to look nicer.
