### ISSUE TITLE
Aether Highland Trees have no snow on them

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#16]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Just a little detail I feel like would make sense in the Aether Highlands as it just feels a little off without it. Would it be possible to have snow generate or spawn on trees in Aether Highlands? I don't have premium yet, so if true can snow also put added to the chad Aether Highland Forest trees?

**Describe alternatives you've considered**
Adapt or change this idea somehow to however you seek fit.

**Additional context**
Pictures below
### Before
![2020-06-13_17 25 46](https://user-images.githubusercontent.com/51402617/84579376-49ec9900-ad9b-11ea-8a93-4170e50a6944.png)
### After
![2020-06-13_17 26 53](https://user-images.githubusercontent.com/51402617/84579378-4eb14d00-ad9b-11ea-9c76-2dcbadca7558.png)

**Comment by dfsek** [comment]
Ah, the snow is no longer able to gen on the trees bc of some performance improvements I made. I will definitely be adding that back.

**Comment by dfsek** [comment]
Will be released with 3.3.0

**Comment by dfsek** [comment]
Released.
