### ISSUE TITLE
Birch Trees in the Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#17]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Some birch trees in the Aether. That's how it is in the overworld with regular forests or should the Aether only have oak and spruce. Not many birch trees considering the amount of trees in the Aether and the ratio of birch trees to oak trees in the Overworld being pretty low. Birch trees probably doesn't need to show up in the Aether Highlands.

**Describe alternatives you've considered**
Change however you like.

**Additional context**
No pictures atm.

**Comment by dfsek** [comment]
We could add a Birch Forest biome too, perhaps

**Comment by DeathShadez** [comment]
That would work.

**Comment by dfsek** [comment]
Released in v3.4.0

**Comment by DeathShadez** [comment]
### Design Concept 
![2020-07-01_22 49 31](https://user-images.githubusercontent.com/51402617/86311059-83236680-bbed-11ea-909d-1845a9c87d6d.png)
![2020-07-01_22 49 46](https://user-images.githubusercontent.com/51402617/86311053-80287600-bbed-11ea-82fc-8bfe1b48fda0.png)
![2020-07-01_22 51 02](https://user-images.githubusercontent.com/51402617/86311057-81f23980-bbed-11ea-81f8-bed989b31bc2.png)
