### ISSUE TITLE
Crashed End Ship (Structure) | End

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#18]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Basically the End Ship, but it has crashed and impacted with the ground forming a crash site. Possibility a chest or just sorta an aesthetic sorta thing. This would also overall be intriguing to find as people may be motivated to find a flying one. Idk about this one, but just an idea I had. Probably very different variations to ensure the crash sites don't look too similar.

**Describe alternatives you've considered**
Change or adapt this idea to however you seek fit.

**Additional context**
No pictures atm.

**Comment by GucciPoochie** [comment]
I love this idea. Like what if we had shipwrecks, but just for the end? Making the ship look like it crashed will be tricky, but do-able. Nonetheless, I shall get to work on it as soon as possible.

**Comment by DeathShadez** [comment]
I know right. Good luck!

**Comment by dfsek** [comment]
I could do something to populate random blocks (purpur blocks, slabs, etc) around the main structure, so it would look more believable, and each one would be different.

**Comment by DeathShadez** [comment]
That would be ingenious!

**Comment by GucciPoochie** [comment]
![wreckedship1](https://user-images.githubusercontent.com/58349185/84592651-1f7ef800-adfc-11ea-9366-77767c90e60d.png)
We're getting somewhere with this. Also, I plan on having a few variantss, like:
- One with a ripped sail
- One that looks blown up (because tnt cannons)
- One that's a combination of the previous two

**Comment by GucciPoochie** [comment]
![2020-06-14_09 07 27](https://user-images.githubusercontent.com/58349185/84598302-975e1a00-ae1e-11ea-880f-c05c0104ad81.png)
The first full ship is done. The line of endstone shows what is undergound. Note that upon generation, random blocks will be replaced with air, giving it a wrecked sort of style

**Comment by DeathShadez** [comment]
This could really give that vibe like when ship wrecks were added in 1.13 for players to explore. I've also thought about some of the crashed ships being angled or completely horizontal, but that may be not necessary due to the rarity of these structures to an extent with good variations already being planned along with it would be kinda difficult due to the small scales of end ships to begin with possibly. Idk.

**Comment by GucciPoochie** [comment]
![2020-06-14_14 09 07](https://user-images.githubusercontent.com/58349185/84604400-a6f35800-ae4a-11ea-8812-6f9bcb320245.png)

**Comment by DeathShadez** [comment]
That looks magnificent! Amazing work!

**Comment by GucciPoochie** [comment]
Making them at an angle was the most painful part, but now that  thats done i can finish the rest of the variants. I should be done in the next few hours.

**Comment by GucciPoochie** [comment]
![blownship3](https://user-images.githubusercontent.com/58349185/84711121-70850e00-af1a-11ea-88fd-a45f87339112.png)
All 8 designs are complete. More might come later, but for now, i think these shall suffice.

**Comment by DeathShadez** [comment]
Nice work. They should definitely do as players are in awe and intrigue when they find these.
