### ISSUE TITLE
Spruce Wood Abandoned Houses (Structure) | Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#19]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Just a little detail in variation for abandoned houses as abandoned houses have just been pretty much just oak. The new addition of spruce trees in the Aether Highlands kinda allows for that possibility and it makes sense for there to be Spruce Wood Abandoned Houses maybe just in the Highlands if anything. I mean it's probably gonna include the same with everything such as a bed, chest, and more except it will be made of spruce material instead of oak. I mean if you want change the architecture to fit colder climate or keep it the same. Your choice.

**Describe alternatives you've considered**
Adapt or change this idea to how you seek fit

**Additional context**
No pictures at the moment.

**Comment by dfsek** [comment]
This would be a nice detail to add. We are currently in the middle of revamping a lot of structures, so we will take this into consideration.

**Comment by GucciPoochie** [comment]
![hehe](https://user-images.githubusercontent.com/58349185/85244532-cc0f3a00-b3f9-11ea-97dc-3a7846089682.png)

**Comment by DeathShadez** [comment]
Definitely fits the colder climate of the Aether Highlands.
