### ISSUE TITLE
Berry Bushes | Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#20]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Berry bushes I feel like could make an appearance in the end possibly. The chances of them generating could be low possibly as it sorta provides a food source for animals "theoretically" and players if that's okay. It could spawn in the _Aether_Highlands_ or probably the _Aether_Highlands_Forest_ as it is a forest where berries typically spawn in the overworld. Your call.

**Describe alternatives you've considered**
Change or adapt this idea to how you seek fit.

**Additional context**
No pictures at the moment.

**Comment by dfsek** [comment]
This will most likely be implemented.

**Comment by dfsek** [comment]
Released in v3.4.0
