### ISSUE TITLE
Ruined Gold Dungeons or Piece of Gold Dungeon (Structure) | Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#21]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
For players that don't have a clue about the BetterEnd plugin or know about it at all, I try to see views from all overall perspectives. For a clueless player who has played vanilla and beaten the enderdragon, they will be introduced to a world of great wonder and intrigue that the BetterEnd plugin introduces. They may come across their first Aether and explore the stuff it has to offer. They may not know about Gold Dungeons existing along with how they contain Elytras. They can certainly ask, but there is a possibility that they continue to go blindly without this sort of knowledge. There could be a ruined Gold Dungeon that has a higher chance of spawning, but doesn't include anything like actual ones, but can be sort of a reminder to that "What if there are actual flying temples?" These ruined gold dungeons don't even have to be big, but are basically a little broken piece of regular Gold Dungeons that gives the image of a temple. Maybe this is probably not necessary and I need sleep, but just a thought. Along with how theoretically are all these temples gonna be in pristine condition or should they all just be in pristine condition as they are sorta mythical in a sense.

**Describe alternatives you've considered**
Adapt or change this idea to however you see fit.

**Additional context**
No pictures at the moment.

**Comment by GucciPoochie** [comment]
Is this sort of thing what you had in mind?
![2020-06-16_18 22 20](https://user-images.githubusercontent.com/58349185/84844151-a996ae80-affe-11ea-8b6c-ae9e15b502df.png)

**Comment by DeathShadez** [comment]
Yea. Precisely.

**Comment by GucciPoochie** [comment]
![2020-06-17_19 05 21](https://user-images.githubusercontent.com/58349185/84969504-b33b1780-b0cd-11ea-973d-cde17439fe93.png)

**Comment by DeathShadez** [comment]
That should work greatly.

**Comment by GucciPoochie** [comment]
This probably won't work. I can't get it to go nice with the grass, and overall just doesn't look great. I will close this issue.

**Comment by DeathShadez** [comment]
I probably should have clarified this in the beginning, but I meant for these Gold Dungeons Ruins to spawn by chance when pristine Gold Dungeons didn't. Alright tho.

**Comment by DeathShadez** [comment]
![2020-06-20_15 49 41](https://user-images.githubusercontent.com/51402617/85210420-b3295a80-b30d-11ea-84e9-be70331d755f.png)
![2020-06-20_15 51 12](https://user-images.githubusercontent.com/51402617/85210437-e370f900-b30d-11ea-99b4-f8978aab8d48.png)
