### ISSUE TITLE
Cobwebs in Caves | Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#24]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I feel like there should be some cobwebs throughout Aether caves that are just enough to make it look ancient as some structures are ancient along with some structures already having cobwebs themselves.

**Describe alternatives you've considered**
Adapt or change this idea as you seek fit.

**Additional context**
Pictures below.
![2020-06-14_07 02 42](https://user-images.githubusercontent.com/51402617/84591525-18acb100-ae0d-11ea-93d4-0c7837fe640d.png)
![2020-06-14_07 01 35](https://user-images.githubusercontent.com/51402617/84591534-2f530800-ae0d-11ea-8ee8-9c67961ce1a1.png)
![2020-06-14_07 02 10](https://user-images.githubusercontent.com/51402617/84591547-4265d800-ae0d-11ea-953d-ff412ed6214e.png)
![2020-06-14_07 01 25](https://user-images.githubusercontent.com/51402617/84591529-219d8280-ae0d-11ea-8948-76d102873a4f.png)

**Comment by dfsek** [comment]
Maybe in the Highlands, idk about the whole aether tho.

**Comment by DeathShadez** [comment]
That would probably work best.

**Comment by dfsek** [comment]
Released in v3.4.0
