### ISSUE TITLE
Dead Bushes | Aether Highlands

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#25]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
I feel like dead bushes with a little less flowers may suit the Aether Highlands better as it looks more sorta like a cold climate and I guess a wasteland vibe. It helps bring a little bit of a difference as both the Aether Highlands and regular Aether would appear to have to same abundance of the same types of flowers. This would probably apply to the Aether Highland Forest as well. Or maybe you want to maintain the mythical feeling of the entire Aether feeling magical or what not. Depends.

**Describe alternatives you've considered**
Adapt or change this idea to however you seek fit.

**Additional context**
### Before
![2020-06-14_07 23 32](https://user-images.githubusercontent.com/51402617/84592138-4eec2f80-ae11-11ea-9b8b-0d77396f14dd.png)
### After
![2020-06-14_07 27 43](https://user-images.githubusercontent.com/51402617/84592101-06cd0d00-ae11-11ea-8e2c-58b38434468f.png)

**Comment by DeathShadez** [comment]
Now that I look at it. It's probably just fine that way it is.

**Comment by dfsek** [comment]
I might have more ferns generate than grass but the dead bushed is a bit much.

**Comment by DeathShadez** [comment]
Yea. I relooked over the differences with dead bushes and I realized that
yea.
