### ISSUE TITLE
Dragon Fortress 

### ISSUE THREAD

**Issue by Vxlt** [dfsek/BetterEnd-Public#29]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be cool if we had a alternate end island that was for a hardcore dragon. Basically a revamp of the main island but with more difficulty and obstacles to defeat the dragon.
**Describe alternatives you've considered**
None
**Additional context**

**Comment by dfsek** [comment]
Where would this island physically be located?
How, specifically would the fight be made more difficult?

**Comment by Vxlt** [comment]
I don't know where it would be located, maybe having it hard to find.

And maybe making a custom mythicalmob dragon?

**Comment by dfsek** [comment]
So it would be a new biome?

And any mythicmobs configuration would be left up to the end users. Dragons are also notoriously difficult to customize.

**Comment by dfsek** [comment]
This is unlikely to work, due not only to the vagueness of the original suggestion, but also to the difficulty of customizing the Ender Dragon, especially when it is not at the Main Island. Feel free to reopen if you have additional input.
