### ISSUE TITLE
Aether biome suggestion

### ISSUE THREAD

**Issue by AbyssalTrench** [dfsek/BetterEnd-Public#3]
- Ability to configure the average size of the aether islands.
- Ability to configure the blocks that aether island is made off.
- Ability to add island spawn frequency.
- Ability to add island spawn higher or lower. 
- Ability to customize clouds more (blocks, size, height) 
- Ability to have smaller islands or huge islands (like actual Aether worlds)

That's all for aether biome! Thanks!

**Comment by dfsek** [comment]
> * Ability to configure the average size of the aether islands.
> * Ability to add island spawn frequency.
> * Ability to add island spawn higher or lower.
> * Ability to have smaller islands or huge islands (like actual Aether worlds)
All of these already exist

> Ability to customize clouds more (blocks, size, height)
This already is partially implemented (you can customize size and height)

**Comment by dfsek** [comment]
As for customizing blocks, what specific options would you like to see?

**Comment by AbyssalTrench** [comment]
Options that I will like to see:

Aesther biome blocks:

**Island top blocks:**
Grass_block:50%
Podzol: 30%

**Island bottom blocks:** 
Stone:100%
#dirt:100%
#soulsand:100%

Aether Highlands blocks:

**Island top blocks:**
Grass_block:50%
Podzol: 30%

**Wasteland blocks**
#additional blocks
Stone_bricks:10%
Gravel:10%

**Island bottom blocks:** 
Stone:100%
#dirt:100%
#soulsand:100%

**Comment by dfsek** [comment]
wym "Wasteland Blocks"?

**Comment by AbyssalTrench** [comment]
I was referring to the new update:

This version adds a new biome, the Aether Highlands!
This biome is a long forgotten wasteland, found occasionally in the Aether. Spruce trees replace regular Oak, and the ground is made of Coarse Dirt, Gravel, and Podzol. The ground is also covered in a thin layer of snow.

Like the wasteland ground is ** made of Coarse Dirt, Gravel, and Podzol. The ground is also covered in a thin layer of snow.** 
The "Wasteland Blocks" option is like the config option for those blocks above ^

**Comment by dfsek** [comment]
Ah, i was confused as you referred to it as the highlands, then the wasteland. Sorry for the confusion!

I'll definitely work on a feature like this tho, it will definitely be useful :)

**Comment by dfsek** [comment]
Since everything not already implemented in this was covered in your other issue, I'm marking this as a duplicate and closing it.
