### ISSUE TITLE
Multi-Room End Houses (Structure)

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#31]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Multi-Room End Houses. Different types of rooms, floors, and sizes. Basically much smaller and better looking cities (or maybe woodland mansions, but there are in the end). The design could probably be made better unlike my designs. Spawner rooms, treasure rooms (booby traps!), staircases, and more. **This might be something of the structure procedural generation for all I know :/**

**Describe alternatives you've considered**
Adapt and change how you seek fit.

**Additional context**
### Design Concepts
![2020-06-20_02 53 55](https://user-images.githubusercontent.com/51402617/85195738-074b2500-b2a3-11ea-92c0-ab96bb7d4a40.png)

![2020-06-20_02 58 32](https://user-images.githubusercontent.com/51402617/85195740-0c0fd900-b2a3-11ea-87d4-89d237f5cb78.png)
Note: Might be too large :/

![2020-06-20_13 57 29](https://user-images.githubusercontent.com/51402617/85208393-0a273380-b2fe-11ea-8751-ee9911eeaf3a.png)

Maybe a different design and style still.

**Comment by dfsek** [comment]
These would be best to do procedurally, that way each is different (although since they are so small, even with procedural generation they will mostly look the same)

**Comment by DeathShadez** [comment]
It would probably be best to have each of these be unique looking, so maybe some changes in design and scaling will make it so.

**Comment by DeathShadez** [comment]
### Dungeons Instead ¯\_(ツ)_/¯
More adjustable, universal, fitting as I can see it. Sorta like Nether Fortresses, but in the End.
![2020-06-20_15 35 22](https://user-images.githubusercontent.com/51402617/85210258-73ae3e80-b30c-11ea-97ee-94a579aa3c44.png)

**Comment by GucciPoochie** [comment]
I don’t know what I’m allowed to say, but we already have plans for this.

**Comment by DeathShadez** [comment]
I already sorta assumed so in the back of my mind. Since the "Multi-Room End Houses" don't seem to work that well in being unique and random, they probably wouldn't work too well overall.
