### ISSUE TITLE
Obsidian Pillars (Structure)

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#32]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Obsidian Pillars that spawn randomly in the end. Basically reuses the obsidian pillars you find on the dragon island, but are of a different design and you find them out in the end dimension.

**Describe alternatives you've considered**
Adapt or change how you seek fit.

**Additional context**
![2020-06-20_17 14 58](https://user-images.githubusercontent.com/51402617/85211735-0f927700-b31a-11ea-9591-776b839ca075.png)
![2020-06-20_17 15 03](https://user-images.githubusercontent.com/51402617/85211711-e245c900-b319-11ea-93c3-5e9127614a61.png)

**Comment by dfsek** [comment]
Isn't this the Shattered End biome? Or do you have something different in mind?

**Comment by DeathShadez** [comment]
Something different.

**Comment by GucciPoochie** [comment]
I never liked this idea, we’ve had it before but it wouldn’t work out. However, I’ve been wanting to make like an obsidian tower or something of the like but I’d need something like voxel sniper to pull it off because the shape is unimaginably hard.

**Comment by DeathShadez** [comment]
Tried out Voxel Sniper for the first time. Can't believe I've never used this useful tool before.
Revised the Obsidian Pillar to have a more rugged look and such for the concept.
![2020-06-20_18 32 37](https://user-images.githubusercontent.com/51402617/85212832-bda31e80-b324-11ea-8cd6-92d58a965011.png)
Probably a larger quality circular pillar would look better however.

**Comment by DeathShadez** [comment]
Bigger magnitude and style.
![2020-06-20_20 09 53](https://user-images.githubusercontent.com/51402617/85213892-4b393b00-b332-11ea-86c4-38b63cbb0142.png)
![2020-06-20_20 11 23](https://user-images.githubusercontent.com/51402617/85213897-5a1fed80-b332-11ea-942e-e17c7c88f142.png)

**Comment by dfsek** [comment]
These don't really work imo as they dominate the scene due to their size. Besides, we have obsidian pillars in the Shattered End, so why have gigantic ones elsewhere? I will be closing this, but feel free to continue discussion/make changes and reopen.
