### ISSUE TITLE
Mushroom Islands | Aether

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#33]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Mushroom Islands in the Aether. These Mushroom Islands will be just like the ones in the Overworld. They will consist of mushrooms and their bigger forms along with mooshrooms. These islands should be remote and cover a small area along with being really rare just like their overworld counterparts. You could make these biomes, but then these would be very small biomes in remote locations or as structures in remote areas of the Aether. Whatever option you see as the most viable.
_**Thoughts: or have you have preferred this idea to be part of an complete Aether world instead?**_

**Describe alternatives you've considered**
Adapt or change this idea to however you seek fit.

**Additional context**
### Mushroom Islands in the Aether
![2020-06-21_13 31 36](https://user-images.githubusercontent.com/51402617/85231335-2d1c1b00-b3c4-11ea-856b-f09e95029535.png)
![2020-06-21_13 31 25](https://user-images.githubusercontent.com/51402617/85231426-dc58f200-b3c4-11ea-8dec-54305b80f109.png)

**Comment by dfsek** [comment]
Due to how I have generation set up, it would be immensely difficult to have single islands be mushroom biomes. I'll see what I can do, as I like this idea a lot and have considered it in the past.

**Comment by dfsek** [comment]
I've thought about this, and although I love the idea, I simply can't think of a way to make it work without immense lag. I'll reopen this if I figure something out... :(
