### ISSUE TITLE
Biome spawn option.

### ISSUE THREAD

**Issue by AbyssalTrench** [dfsek/BetterEnd-Public#4]
- Ability to enable and disable which biomes can spawn, and which cannot.
- % or chance of biome to spawn. For example 
Void spawn chance: 50%
Aether spawn chance: 30%
- Ability to have per world enable / disable. For example:

Config A:

Schematic spawn: True
Ruins spawn: True
Void biome: True
End biome: True
Aether: false

Worlds that this config will be enabled in:

world_the_end

Config B:

Schematic spawn: False
Ruins spawn: False
Void biome: False
End biome: False
Aether: True

Worlds that this config will be enabled in:

some_world

**Comment by dfsek** [comment]
Most of these would be implementable, and will be worked on.

**Comment by dfsek** [comment]
This most likely will not be worked on in the near future. Will reopen if it ever begins development.
