### ISSUE TITLE
1.16 Quartz Bricks Integration | Gold Dungeon?

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#43]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I know there is a plan to implement 1.16 blocks probably in the far future, so this idea is just here to settle about or worked about till then. The gold dungeons are pretty mythical looking as it is, but what if Quartz bricks could be added into the equation (design). Though this would have probably be a 1.16+ version design. Quartz bricks could also be used for other implementations in the future.

**Describe alternatives you've considered**
Adapt or change to how you seek fit.

**Additional context**
### Quartz Palette
![2020-06-26_16 23 35](https://user-images.githubusercontent.com/51402617/85904550-03edf700-b7d7-11ea-8961-fb0af1ea09f8.png)

**Comment by GucciPoochie** [comment]
Yeah I don’t think I will implement them, the design of the gold dungeon is fine as it is, and the quartz brick looks yucky. Plus the fact that we’re not planning on implementing 1.16 blocks for a while. Imma close this issue, as there’s not much more to be said.
