### ISSUE TITLE
Void Field Biome

### ISSUE THREAD

**Issue by DeathShadez** [dfsek/BetterEnd-Public#8]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
A biome called _Void_Field_ that is filled with these glowstone glass crystals that are idk..."Void Stars." Just a cool looking biome that adds more life to the endless void. The "Void Stars" can span from the bottom to the top of the world maybe or just have a large area in which they are concentrated in. Can even be used as a sort of obstacle to elytra flyers and possibly other stuff in the future.

**Describe alternatives you've considered**
Change the name of the biome and the look of the "Void Stars" if you want or the parameters in which this biome will work to which you see fit

**Additional context**
Pictures below of my sample "Void Stars"

### _Void_Field_ [no shader]
![2020-06-10_07 17 16](https://user-images.githubusercontent.com/51402617/84262003-cefd5700-aaea-11ea-8aa2-85527e71c487.png)

### _Void_Field_ [shader]
![2020-06-10_07 16 50](https://user-images.githubusercontent.com/51402617/84262094-f8b67e00-aaea-11ea-95a0-01ae7b6a53ff.png)

### Void Star A
![2020-06-10_07 18 01](https://user-images.githubusercontent.com/51402617/84262371-7ed2c480-aaeb-11ea-916f-76fcb04248a4.png)

### Void Star B
![2020-06-10_07 18 31](https://user-images.githubusercontent.com/51402617/84262417-9447ee80-aaeb-11ea-820a-8fcd0b849d3e.png)

### Void Star Spiker
![2020-06-10_07 18 09](https://user-images.githubusercontent.com/51402617/84262422-96aa4880-aaeb-11ea-8a18-89976a09f449.png)

### Void Star Crystal
![2020-06-10_07 17 24](https://user-images.githubusercontent.com/51402617/84262428-99a53900-aaeb-11ea-90a7-444694c678ad.png)

I might add more Void Star types later.

Adapt or change this idea to how you see fit.

**Comment by dfsek** [comment]
Implemented, and will be released with next version. (as part of the free version)

**Comment by dfsek** [comment]
Implemented in 3.2
